### ISSUE TITLE
sitenow_media_permissions is overridden

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/sitenow_standard_profile#37]
![image](https://cloud.githubusercontent.com/assets/1068523/21394502/7ae32884-c75e-11e6-9d89-6d3ad2767776.png)

**Comment by genjohnson** [comment]
I think @brandonneil and I talked about this awhile ago (if it wasn't this issue specifically it was something similar), and we discussed whether it made sense to have these permissions featurized since some websites have other roles or do not use both the _webmaster_ and _editor_ roles. I think this is more of an issue for Custom sites since Standard sites use specific roles & permissions, but the default permissions are not currently set well for new Custom sites.

I propose that we remove sitenow_media_permissions and instead set the permissions during site install from sitenow_standard_profile/sitenow_profile or sitenow_media to standardize how the permissions are initially set for both Custom and Standard sites.
